### ISSUE TITLE
CF7 plugin giving error 500

### ISSUE THREAD

**Issue by klikk** [macbookandrew/cf7-authorize-net#1]
I am not sure if this plugin is updated anymore or not, I will try to look into fixing this problem myself as well, but maybe you have a quick solution already. Thanks for looking into this.

Basically the plugin is giving CF7 an internal server error on submit:

VM4228:1 POST domain/wp-json/contact-form-7/v1/contact-forms/4675/feedback 500 ()

**Comment by klikk** [comment]
If you don't have time I would be more than happy to look into fixing this, maybe you can give me some hints how to start / how to debug?

**Comment by macbookandrew** [comment]
@klikk Start by looking in the root folder of your WordPress installation for a file named `error_log`. Then send a submission causing the error and check last line(s) in `error_log` for details on what went wrong.

**Comment by klikk** [comment]
Thank you for the insights, I have managed to fix the issue, it was a php incompatibility problem... Thanks again!

**Comment by awesome1128** [comment]
> incompatibility

How did you fix that issue? I am facing completely same issue now.
Thank you.

**Comment by macbookandrew** [comment]
@klikk See above

**Comment by RonaraT** [comment]
I also encountered this problem, but there is no conflict with the php version, I checked on a test site. And the problem appeared after transferring to hosting and connecting to the domain. Maybe someone can tell me where to "dig"?

**Comment by macbookandrew** [comment]
See [above](https://github.com/macbookandrew/cf7-authorize-net/issues/1#issuecomment-405727237)
